### ISSUE TITLE
FCParts.GenerateParts() is missing

### ISSUE THREAD

**Issue by Nick-Mazuk** [rpatters1/rgpluaclassbrowser#12]
The changelog for v0.62 says there's a new method `FCParts.GenerateParts()`, however I don't see that in the class browser.

I'm using the most recent version of the class browser (pulled today).

**Comment by rpatters1** [comment]
It's there on mine. It's a class method. Are you using the `jwtagfile.xml` for 0.62?

**Comment by Nick-Mazuk** [comment]
Figured it out. Yes, I am using that version of `jwtagfile.xml`, but your message reminded me that I needed update RGP Lua itself.

It's neat that the class browser will only show methods the running version of RGP Lua supports.

To prevent further confusion, would it be possible to add a quick piece of text to the dialog to show the current version of the class browser and RGP Lua?

Closing in the meantime since my original issue is solved. Feel free to reopen.
